# dockercompose file
version: '3'
services:
  auth-service:
    build: 
      context: ./
      dockerfile: ./auth-service/Dockerfile
    ports:
      - 3000:80
    environment:
      - COGNITO_CLIENT_ID=41i6hnruc402hpn9ffihn0nrn2
      - COGNITO_USER_POOL_ID=ap-southeast-2_5mUCnh2Fg

  bff-service:
    build: 
      context: ./
      dockerfile: ./bff-service/Dockerfile
    ports:
      - 3001:80

  notes-service:
    build: 
      context: ./
      dockerfile: ./notes-service/Dockerfile
    ports:
      - 3002:80
    environment:
     - MONGO_URI=mongodb://admin:password@mongo:27017/notes?authSource=admin

  mongo:
    # image: 329045634983.dkr.ecr.ap-southeast-2.amazonaws.com/mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    restart: always
    


