# dockercompose file
version: '3'
services:
  auth-service:
    build: 
      context: ./
      dockerfile: ./auth-service/Dockerfile
    ports:
      - 3000:3000
    environment:
      - COGNITO_CLIENT_ID=41i6hnruc402hpn9ffihn0nrn2
      - COGNITO_USER_POOL_ID=ap-southeast-2_5mUCnh2Fg


  bff-service:
    build: 
      context: ./
      dockerfile: ./bff-service/Dockerfile
    ports:
      - 3001:3000

  notes-service:
    build: 
      context: ./
      dockerfile: ./notes-service/Dockerfile
    ports:
      - 3002:3000


