# dockercompose file
version: '3'
services:
  auth-service:
    build: 
      context: ./
      dockerfile: ./auth-service/Dockerfile
    ports:
      - 3000:3000

  bff-service:
    build: 
      context: ./
      dockerfile: ./bff-service/Dockerfile
    ports:
      - 3001:3000

  notes-service:
    build: 
      context: ./
      dockerfile: ./notes-service/Dockerfile
    ports:
      - 3002:3000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    depends_on:
      - mongo
    restart: always



