# dockercompose file
version: '3'
services:
  auth-service:
    build: 
      context: ./
      dockerfile: ./auth-service/Dockerfile
    ports:
      - 3000:3000

  bff-service:
    build: 
      context: ./
      dockerfile: ./bff-service/Dockerfile
    ports:
      - 3001:3000

  notes-service:
    build: 
      context: ./
      dockerfile: ./notes-service/Dockerfile
    ports:
      - 3002:3000


