# kubernetes deployment configuration file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
        - name: notes-service
          image: notes-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/notes
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongo-secret
          secret:
            secretName: mongo-secret
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo.config: |
    storage:
      dbPath: /data/db
      engine: wiredTiger
    net:
      bindIp: 0.0.0.0
      port: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo.user: <base64-encoded-mongo-user>
  mongo.password: <base64-encoded-mongo-password>
