apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
      - name: notes-service
        image: 329045634983.dkr.ecr.ap-southeast-2.amazonaws.com/notes-service
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password@mongo:27017/notes?authSource=admin"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

      volumes:
      - name: mongo-data
        emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: 329045634983.dkr.ecr.ap-southeast-2.amazonaws.com/mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: mongo-data
        emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: 329045634983.dkr.ecr.ap-southeast-2.amazonaws.com/mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "password"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongo"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"