apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  selector:
    app: notes-service
  ports:
    - name: http
      port: 80
      targetPort: 80
      # should be available outside the cluster
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
