version: 0.2
# this buildspec deployes cloudformation stack

phases:
  pre_build:
    commands:
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_REGION
      - echo $CF_STACK_NAME
      - echo $CF_TEMPLATE_FILE
      - echo $CF_PARAMETERS

      # check aws cli version
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Deploying the CloudFormation stack...

      # Deploy the CloudFormation stack
      - aws cloudformation deploy --stack-name $CF_STACK_NAME --template-file $CF_TEMPLATE_FILE --parameter-overrides $CF_PARAMETERS --capabilities CAPABILITY_NAMED_IAM || exit 0

  post_build:
    commands:
      - echo Build completed on `date`
      - echo CloudFormation stack deployed successfully
