AWSTemplateFormatVersion: "2010-09-09"
Description: CICD Pipeline

# defining parameters
Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub owner
  GitHubRepo:
    Type: String
    Description: GitHub repo
  GitHubBranch:
    Type: String
    Description: GitHub branch
  GitHubToken:
    Type: String
    Description: GitHub token

# defining pipeline resources
Resources:
  # this s3 bucket will have the built artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-artifacts

  # this is the codepipeline project
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        # ===== SOURCE PHASE =====
        # sourcing resources from github
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Sub ${GitHubOwner}
                Repo: !Sub ${GitHubRepo}
                Branch: !Sub ${GitHubBranch}
                OAuthToken: !Sub ${GitHubToken}
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        # ===== SERVICE BUILD PHASE =====
        - Name: BuildCode
          Actions:
            - Name: BuildAuthService
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProjectAuthService
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputAuthService
              RunOrder: 1
            - Name: BuildBffService
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProjectBffService
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputBffService
              RunOrder: 1
            - Name: BuildNotesService
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProjectNotesService
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputNotesService
              RunOrder: 1
            - Name: BuildLogsService
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProjectLogsService
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputLogsService
              RunOrder: 1

        # ==== INFRA BUILD PHASE ====
        - Name: BuildInfra
          Actions:
            - Name: BuildProjectDataLayer
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProjectDataLayer
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutputInfraDataLayer
              RunOrder: 1

  # ======== SERVICE BUILD PROJECTS ========
  # this is the codebuild project for auth-service
  BuildProjectAuthService:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-auth-service
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ECR_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: SERVICE_NAME
            Value: auth-service
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  # this the ecr repository for auth-service
  EcrRepositoryAuthService:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: auth-service

  # this is the codebuild project for bff-service
  BuildProjectBffService:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-bff-service
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ECR_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: SERVICE_NAME
            Value: bff-service
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  # this the ecr repository for bff-service
  EcrRepositoryBffService:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bff-service

  # this is the codebuild project for notes-service
  BuildProjectNotesService:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-notes-service
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ECR_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: SERVICE_NAME
            Value: notes-service
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  # this the ecr repository for notes-service
  EcrRepositoryNotesService:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: notes-service

  # this is the codebuild project for logs-service
  BuildProjectLogsService:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-logs-service
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ECR_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: SERVICE_NAME
            Value: logs-service
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  # this the ecr repository for logs-service
  EcrRepositoryLogsService:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: logs-service

  # ======== INFRA BUILD PROJECTS ========
  # this is the codebuild project for data layer
  BuildProjectDataLayer:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build-data-layer
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: CF_STACK_NAME
            Value: !Sub ${AWS::StackName}-data-layer
          - Name: CF_TEMPLATE_FILE
            Value: ./cloudformation/data.yml
          - Name: CF_PARAMETERS
            Value: !Sub TableName=${AWS::StackName}-notes
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
      ServiceRole: !GetAtt BuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: ./cloudformation/buildspec.yml
      TimeoutInMinutes: 5

  # ======== IAM ROLES ========
  # this is the role that the codebuild project will assume
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-codebuild-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - codecommit:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - codepipeline:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cognito-idp:*
                Resource: "*"

  # this is the role that the pipeline will assume
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-codepipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - codecommit:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - codepipeline:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: "*"

Outputs:
  # ecr repositories
  EcrRepositoryBffService:
    Description: ECR repository for bff-service
    Value: !Ref EcrRepositoryBffService

  EcrRepositoryNotesService:
    Description: ECR repository for notes-service
    Value: !Ref EcrRepositoryNotesService

  EcrRepositoryLogsService:
    Description: ECR repository for logs-service
    Value: !Ref EcrRepositoryLogsService

  # codepipeline
  Pipeline:
    Description: CodePipeline
    Value: !Ref Pipeline

  # codebuild projects
  BuildProjectBffService:
    Description: CodeBuild project for bff-service
    Value: !Ref BuildProjectBffService

  BuildProjectNotesService:
    Description: CodeBuild project for notes-service
    Value: !Ref BuildProjectNotesService

  BuildProjectLogsService:
    Description: CodeBuild project for logs-service
    Value: !Ref BuildProjectLogsService

  BuildProjectDataLayer:
    Description: CodeBuild project for data-layer
    Value: !Ref BuildProjectDataLayer
