# cloudformation to create dynamodb table for notes
# has a schema of
# 1. ownerid (string) - primary key,
# 2. created_at (string) - timestamp, sort key
# 3. title (string),
# 4. content (string)
# 5. updated_at (string) - timestamp

AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB table for notes and Cognito for user management"

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: notes-table

Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
        - AttributeName: created
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-cognito-pool"
      UsernameAttributes:
        - "email"
      AutoVerifiedAttributes:
        - "email"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      VerificationMessageTemplate:
        EmailMessage: "Click the following link to verify your email address: {####}"
        EmailSubject: "Verify your email for our app"
      EmailVerificationSubject: "Verify your email for our app"
      EmailVerificationMessage: "Click the following link to verify your email address: {####}"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - AttributeDataType: "String"
          Name: "email"
          Required: true

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${AWS::StackName}-cognito-client"
      GenerateSecret: false
      ExplicitAuthFlows:
        - "USER_PASSWORD_AUTH"
      AllowedOAuthFlows:
        - "code"
      AllowedOAuthScopes:
        - "email"
        - "openid"
        - "profile"
      CallbackURLs:
        - "https://example.com"


# output the table name
Outputs:
  TableName:
    Value: !Ref NotesTable
    Description: Name of the DynamoDB table

  UserPoolId:
    Value: !Ref UserPool

  UserPoolClientId:
    Value: !Ref UserPoolClient
